### ISSUE TITLE
Unable to convert Night of Azure2's ebm file

### ISSUE THREAD

**Issue by imrutel** [VitaSmith/gust_tools#15]
ERROR: Don't know how to handle this type of .ebm file

However, it can be converted by adding 4 bytes.

// gust_ebm.c - Line 102

ebm_header[++j] = (uint32_t)json_object_get_number(json_message, "msg_id");
// if (NOA2 ebm file) {
ebm_header[++j] = (uint32_t)json_object_get_number(json_message, "unknown");

ebm_header[++j] = (uint32_t)json_object_get_number(json_message, "unknown4");

[JPN_EVENT_MESSAGE_MM00_010.zip](https://github.com/VitaSmith/gust_tools/files/4678655/JPN_EVENT_MESSAGE_MM00_010.zip)

**Comment by VitaSmith** [comment]
Well, the problem is really this:

```C
// if (NOA2 ebm file)
```

Unless there is a programmatic way to tell a NOA2 ebm file from a regular ebm file, I can't really add support for those outside of using a commandline switch, and I'm prefer to avoid that.

Is there anything you can find that could help tell NOA2 and other files apart?

**Comment by VitaSmith** [comment]
Looking at the problem more closely, it has nothing to do with needing an extra field between `msg_id` and `unknown4`. Instead the difference is that there is 32-bit of extra padding after the message.
