### ISSUE TITLE
Please add .e seed. (night of azure 2)

### ISSUE THREAD

**Issue by caglia** [VitaSmith/gust_tools#2]
I want to decode the xml.e file for night of Azure 2.
Can you add seed of night of Azure 2?

**Comment by VitaSmith** [comment]
Let me see what I can do...

**Comment by VitaSmith** [comment]
Well, if NOA2 was anything like the other Gust games, then adding the following to the `gust_enc.json` would work:
```
        {
            "id": "NOA2",
            "name": "Nights of Azure 2",
            "main": [
                0x728f,
                0xc979,
                0x6d73
            ],
            "table": [
                0xa9bb,
                0x892d,
                0x8939
            ],
            "length": [
                0x1f,
                0x1d,
                0x17
            ],
            "fence": 0x1352
        },
```
However, it looks like Gust added some extra calls (the bit scrambler seems to be called a few more times compared to the other games) and I just don't think I'm gonna bother trying to figure out that one.

If someone feels like investing their time and send a patch to add NOA2 support to `gust_enc`, I'll happily apply it. Otherwise, sorry, but it's very unlikely that I'll ever have spare time to spend on this.

Closing this issue.

**Comment by VitaSmith** [comment]
Actually, now that I also looked at the Night Of Azure executable (which is less of a mess than the NOA2 one), here is what you need in your `gust_enc.json` for NOA/NOA2:
```
        {
            "id": "NOA",
            "name": "Nights of Azure / Nights of Azure 2",
            "main": [
                0x6d73,
                0xc979,
                0x728f
            ],
            "table": [
                0xa9bb,
                0x892d,
                0x8939
            ],
            "length": [
                0x1f,
                0x1d,
                0x17
            ],
            "fence": 0x1352
        },
```
My seeds were correct, it's just the flow of execution that was wrong...

I'll add this to the next release.

**Comment by VitaSmith** [comment]
This should work with newly release 1.5 version of the tools. Enjoy!
