### ISSUE TITLE
Atelier Sophie (A17) *.EBD files

### ISSUE THREAD

**Issue by NoNameUserDev** [VitaSmith/gust_tools#20]
Hi guys! I really appreciate all of you guys for these tools! And there are *.ebd files, which are probably Japanese texts. I want to translate from Japanese, so can you explore this format too? I'm not a programmer, but at least I've already done things like extracting and repacking.

**Comment by VitaSmith** [comment]
As much as I'd like to support everything under the sun, there's only so much time I can invest in these tools, and a quick look at the `.edb` files from Sophie indicates that, unlike what was the case for the other formats we added, there's way too many fields that can't easily be guessed from `.edb` files and that would take a lot of time to investigate.

If someone can provide a complete description of the `.edb` data format, I don't mind adding a tool. But otherwise I'm not planning to do that.

**Comment by NoNameUserDev** [comment]
Oh, is that so... Ok, never mind! I can feel how it can be pain in the ass 😅 All I have to do is translate from English, though I can see and compare for the original Japanese in the game, but it pain in the ass, too ._.
Good luck to you guys! 😊👍
