### ISSUE TITLE
Fairy Tail g1t Files

### ISSUE THREAD

**Issue by Misaki-Ki** [VitaSmith/gust_tools#22]
As requested, here is the current status for Fairy Tail:
Albedo Textures currently work, they're typically stored as DXT1 with 2-3 mipmaps or as BC7. 
Occlusion Textures do not work. These are stored as BC4.

It's worth noting I have not been able to get directories to extract. It gives me an error about the json not existing, which I believe is used for recreating a g1t? 

Included in the attachment is a sample of each of the two types, and a folder containing randomly chosen sample files. 

[FT G1T.zip](https://github.com/VitaSmith/gust_tools/files/5075164/FT.G1T.zip)

**Comment by VitaSmith** [comment]
Many thanks for the report. I'll take a look when I get a chance.

Can you provide a screenshot/text copy of that json error as well, so that I can be sure what we're talking about?

**Comment by VitaSmith** [comment]
Or, now that I'm re-reading what you write, it seems that you are under the impression that you can just take a directory, and `gust_g1t` will extract all the `.g1t` files from it. I'm afraid that's not how it works since we reserve directory drag and drop for recreating a `.g1t` from the previously extracted textures.

If you want to extract all the `.g1t` from one directory, you should script it with a batch file that does something like:
For all files in this directory, if the file has a `.g1t` extension, call `gust_g1t` with it.

**Comment by VitaSmith** [comment]
Here's an example of a script for mass extraction of `g1t` files:

```
@echo off
forfiles /P %1 /s /m *.g1t /c "cmd /c \"\"%CD%\gust_g1t.exe\" @path\""
pause
```

Just copy the above as `extract_g1t.cmd`, make sure you have `gust_g1t.exe` in the same directory as the `.cmd` you created and just drag and drop a directory with a bunch of `.g1t`'s on top of it.

**Comment by pbatard** [comment]
Okay, I'm going to assume that the only issue is with type `0x5C` textures, because I'm not seeing much of a problem with the other files (if there is, you're going to have to be more specific about what these issues are, because the generated `.dds` all look fine to me when opening them in Visual Studio):

```
C:\Projects\gust_tools\FT>gust_g1t.exe MPR_Eternal_Character_pcm002erzad_body_kidsocc.g1t
Extracting 'MPR_Eternal_Character_pcm002erzad_body_kidsocc.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
ERROR: Unsupported texture type (0x5C)

C:\Projects\gust_tools\FT>gust_g1t.exe MPR_Eternal_Character_pcm002erzah_body_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzah_body_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x59 0x00000024 0x00028034 MPR_Eternal_Character_pcm002erzah_body_kidsalb\000.dds 512x512    2       Y

C:\Projects\gust_tools\FT>cd test

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pc002erza_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pc002erza_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                 DIMENSIONS MIPMAPS SUPPORTED?
0x5f 0x00000024 0x00150034 MPR_Eternal_Character_pc002erza_skin_kidsalb\000.dds 1024x1024  3       Y

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pcm002erzab_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzab_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x5f 0x00000024 0x00150034 MPR_Eternal_Character_pcm002erzab_skin_kidsalb\000.dds 1024x1024  3       Y

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pcm002erzad_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzad_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x59 0x00000024 0x000a8034 MPR_Eternal_Character_pcm002erzad_skin_kidsalb\000.dds 1024x1024  3       Y
```

Besides trying to add support to type `0x5C`, the only thing I can work with, if the generated `.dds` is not what you want, is if you provide the `.dds` that you need. Please bear in mind that I have next to zero knowledge about 3D graphics, texture elements and whatnot. However, if you give me the output you want from a specific input, I may be able to figure out a way to generate it.

**Comment by VitaSmith** [comment]
Okay, I'm going to assume that the only issue is with type `0x5C` textures, because I'm not seeing much of a problem with the other files (if there is, you're going to have to be more specific about what these issues are, because the generated `.dds` all look fine to me when opening them in Visual Studio):

```
C:\Projects\gust_tools\FT>gust_g1t.exe MPR_Eternal_Character_pcm002erzad_body_kidsocc.g1t
Extracting 'MPR_Eternal_Character_pcm002erzad_body_kidsocc.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
ERROR: Unsupported texture type (0x5C)

C:\Projects\gust_tools\FT>gust_g1t.exe MPR_Eternal_Character_pcm002erzah_body_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzah_body_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x59 0x00000024 0x00028034 MPR_Eternal_Character_pcm002erzah_body_kidsalb\000.dds 512x512    2       Y

C:\Projects\gust_tools\FT>cd test

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pc002erza_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pc002erza_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                 DIMENSIONS MIPMAPS SUPPORTED?
0x5f 0x00000024 0x00150034 MPR_Eternal_Character_pc002erza_skin_kidsalb\000.dds 1024x1024  3       Y

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pcm002erzab_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzab_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x5f 0x00000024 0x00150034 MPR_Eternal_Character_pcm002erzab_skin_kidsalb\000.dds 1024x1024  3       Y

C:\Projects\gust_tools\FT\test>gust_g1t.exe MPR_Eternal_Character_pcm002erzad_skin_kidsalb.g1t
Extracting 'MPR_Eternal_Character_pcm002erzad_skin_kidsalb.g1t'...
TYPE OFFSET     SIZE       NAME                                                   DIMENSIONS MIPMAPS SUPPORTED?
0x59 0x00000024 0x000a8034 MPR_Eternal_Character_pcm002erzad_skin_kidsalb\000.dds 1024x1024  3       Y
```

Besides trying to add support to type `0x5C`, the only thing I can work with, if the generated `.dds` is not what you want, is if you provide the `.dds` that you need. Please bear in mind that I have next to zero knowledge about 3D graphics, texture elements and whatnot. However, if you give me the output you want from a specific input, I may be able to figure out a way to generate it.

**Comment by VitaSmith** [comment]
Type `0x5c` seems easy enough to add. Does the following look okay to you?

![000](https://user-images.githubusercontent.com/32225969/90280811-75efcd80-de63-11ea-9bc4-12cfd0b8584a.png)

You can find the associated `.dds` in [MPR_Eternal_Character_pcm002erzad_body_kidsocc.zip](https://github.com/VitaSmith/gust_tools/files/5076370/MPR_Eternal_Character_pcm002erzad_body_kidsocc.zip).

**Comment by Misaki-Ki** [comment]
It seems fine, I can't see any difference in a comparison between that and another version of the file I have. This is the only texture type I ran across that didn't work, so that should be it. 

> 
> 
> Here's an example of a script for mass extraction of `g1t` files:
> 
> ```
> @echo off
> forfiles /p %1 /s /m *.g1t /c "cmd /c \"\"%CD%\gust_g1t.exe\" @path\""
> pause
> ```
> 
> Just copy the above into a text file, rename it as `extract_g1t.cmd`, make sure you have `gust_g1t.exe` in the same directory as the `.cmd` you created and just drag and drop a directory with a bunch of `.g1t`'s on top of it.

Yeah, I use forfiles for many things. It's a lifesaver!

**Comment by VitaSmith** [comment]
Reopening this issue, as I have not yet officially released a version that adds support to type `0x5c`. I will do that shortly and close this issue when it's done.

**Comment by VitaSmith** [comment]
Just gonna mention that I improved `gust_g1t` as it had a couple issues when it comes to Fairy Tail textures. [Version 1.25](https://github.com/VitaSmith/gust_tools/releases/tag/v1.25) should be able to decode and reencode `.g1t` files better for that game.
