### ISSUE TITLE
How the game handle font ?

### ISSUE THREAD

**Issue by BelovedTomboyishGirl** [VitaSmith/gust_tools#26]
Hello,

First sorry for using this as an issue, because it's not really related to the tools you provided,
It's more a question around the engine and how it read font textures,

I'm developping a translation tool for Atelier Ryza Ever darkness, and in some language, there is different character that aren't handled by the game currently, i've the font files, i can modify it to add the character, but i don't know where the game handle the position in the texture for showing the char.

Thanks for informations, and for the tools you provide.
And once again sorry for using issues for that.

**Comment by yretenai** [comment]
I believe it hardcodes a character table for the 2 main fonts. At least the filenames are directly referenced by the assembly, and I can't find something that resembles a character table in the game files.

**Comment by BelovedTomboyishGirl** [comment]
> 
> 
> I believe it hardcodes a character table for the 2 main fonts. At least the filenames are directly referenced by the assembly, and I can't find something that resembles a character table in the game files.

That's what I feared, i'll take a look at the assembly but, i don't hope for much,
For most of the textures, table is on data/saves/ (example: Data\saves\ui_en\gen_styles) but yeah for font looks like it's different.
Thanks for info.

**Comment by BelovedTomboyishGirl** [comment]
I've find some things that are maybe related to the char table
![image](https://user-images.githubusercontent.com/43587824/105766850-8b147080-5f5a-11eb-992d-35176c8fb733.png)
I keep digging around and see if i can find something for resolve my problem, but reverse engineering isn't my cup of tea.

**Comment by VitaSmith** [comment]
I'm going to close this issue, if that's okay with you, as this is tangent to gust_tools and I'm afraid that you will have to do your homework yourself on this.

**Comment by marcussacana** [comment]
@BelovedTomboyishGirl I did your 'home work' here  🤣 ,
I don't think will work with any gust game but I at least tested with 3 games, Atelier Sofia, Atelier Firis and Night of Azure.
Anyway, I published here: https://github.com/marcussacana/AtelierManager/, you still need the tool made by our friend @VitaSmith to extract the game files and the font texture, since my Font tool don't handle the g1t format.
By the way VitaSmith, thank you for your tool, that helped me a lot.
![GustFontEditor_2yITWf9b0q](https://user-images.githubusercontent.com/10576957/116820604-552feb00-ab4c-11eb-9d35-45ffa6489c62.png)
![Captura de Tela (21)](https://user-images.githubusercontent.com/10576957/116820618-61b44380-ab4c-11eb-963f-27b1c7df29e5.png)
![Captura de Tela (16)](https://user-images.githubusercontent.com/10576957/116820628-67aa2480-ab4c-11eb-9e37-f300813db8fd.png)
