### ISSUE TITLE
Ryza 2 .ebm errors

### ISSUE THREAD

**Issue by wwwklopar** [VitaSmith/gust_tools#29]
Hello!
Some .ebm files from Ryza 2 are processing with same type or error
There are quite a lot of them to capture, but here is screenshot with some of files.
![Screenshot_2](https://user-images.githubusercontent.com/45036201/106384601-cdb3ce00-63dc-11eb-8889-ff4e41c0a58a.png)

**Comment by wwwklopar** [comment]
And some files have this type or error
![Screenshot_4](https://user-images.githubusercontent.com/45036201/106386905-4704ee00-63e8-11eb-8f41-8e2561a420a2.png)

**Comment by VitaSmith** [comment]
This should be fixed in the new release of gust_tools.

Note that some of these files have extra data appended after the bulk of the messages, that I have no idea what it is used for and that is therefore not stored or reconstructed. This means that the `.ebm` recreated by `gust_ebm` may very well not work at all with the game.

However, at this stage, I consider that I have gone as far as I am willing to go with `.ebm` support, so, if more is needed, I will kindly ask that someone use their own time to figure out what extra processing might be needed, and send a Pull Request to add it to the utility.
