### ISSUE TITLE
g1t doesn't repack properly.

### ISSUE THREAD

**Issue by SoulMystique** [VitaSmith/gust_tools#4]
The tool used for unpacking/repacking g1t files unpacks them fine, but it has an issue during repacking that can make the file unusable, even if you haven't edited any of the files.

**Comment by VitaSmith** [comment]
Can you point to an example of game/g1t file that you had trouble with. I'm afraid you're providing too little information for me to look into that issue.

**Comment by VitaSmith** [comment]
I'm going to assume that this is the same issue as #3, so I'm going to close this one. If not, feel free to open a new issue, but please make sure you provide the output from `gust_g1t` when unpacking and repacking, and also indicate precisely the game, `.pak` and `.g1t` location in the `.pak` so that I can try to replicate the issue.

**Comment by VitaSmith** [comment]
This should work with newly release 1.5 version of the tools. Enjoy!
