### ISSUE TITLE
Failed to unpack PACK03.PAK in Atelier Ryza ver 1.08

### ISSUE THREAD

**Issue by jutongpan** [VitaSmith/gust_tools#41]
PACK03.PAK was added in Version 1.08 of Atelier Ryza - Ever Darkness and the Secret Hideout.
Trying to unpack it using gust_pak.exe gives the following error:

```
Extracting 'PACK03.PAK'...
Detected A17/32-bit PAK format

OFFSET    SIZE     NAME
000000150 0014c303 \data\x64\character\pc00k\pc00k_model.elixir.gz*
000000150 00000000 
ERROR: Can't create file 'path_omitted\'

Press any key to continue...
```

I attach PACK03.PAK file here.
[PACK03.zip](https://github.com/VitaSmith/gust_tools/files/6679762/PACK03.zip)

**Comment by VitaSmith** [comment]
Thanks for the report. `PACK03.PAK` must be a DLC file, because I have the Steam version of Atelier Ryza (but not all the DLC), and I don't have that file even though I am running version 1.08.

At any rate, the issue is this:
```
Detected A17/32-bit PAK format
```
It should say instead:
```
Detected A18/64-bit PAK format
```

So it looks like my autodetection of 64-bit PAK format needs a little adjusting. I should have a fix for that soon.

**Comment by VitaSmith** [comment]
The very latest release should extract the files properly now.

**Comment by jutongpan** [comment]
Thanks! The latest release works great.
