### ISSUE TITLE
Support extract/repack g1t files from Fatal Frame: Maiden of Black Water PC version

### ISSUE THREAD

**Issue by jchoi071** [VitaSmith/gust_tools#48]
gust_g1t can't extract the g1t files from this game; then again, it literally just came out a few days ago. The error that comes up is "ERROR: Can't handle G1T files with extra content". The Project G1M plugin for Noesis can extract the files perfectly fine, though it doesn't have a way to repack the result into a g1t file.

[I've attached a g1t from this game if you need it.](https://github.com/VitaSmith/gust_tools/files/7447952/H_MIU_A.zip)

**Comment by yretenai** [comment]
The extra data exists after the offset list (highlighted.)
![image](https://user-images.githubusercontent.com/614231/139567481-a0f0e630-5782-47ff-a23d-e87c58cd06a4.png)
Setting the extra size field (at offset 18h) to zero will make gust_g1t process the files.

**Comment by VitaSmith** [comment]
Thanks for the report. It looks like the extra section is for structures that have an extra flag applied into what I thought was an [`unused` byte](https://github.com/VitaSmith/gust_tools/blob/d2be1f9478c60b6bdf4a4dda5c987c7f5e5f67c2/gust_g1t.c#L74) but which seems to be an extension of the rest of the texture flags.

The reason I am deducing this is because I can count 5 textures with the extra bit set, and we have exactly 5x12 repeating bytes in the global extra data.

I have therefore updated `gust_g1t` to take into account these findings, and I have confirmed that it should be able to unpack and repack the file you attached exactly. Now of course, if you do modify the texture to which the extra global data applies, I make no promise that the repacked `.g1t` will work, since we still have no clue what this extra global data is meant to be used for, in relation to the texture.
