### ISSUE TITLE
Support G1M for BLUE REFLECTION Second Light

### ISSUE THREAD

**Issue by asuka-aurora** [VitaSmith/gust_tools#53]
Thank you for your gust_tools now i can edit many thing in KT games, but i've met a trouble at G1M files. The version of G1M and the files inside just like G1MF and so on always changed. But i found [a video](https://b23.tv/yTphHYi), made something from BLUE REFLECTION to DOA6. And if i want to make some BLUE REFLECTION clothes to BLUE REFLECTION Second Light, could you give me some suggestions？
And i think you have found the game have files of Mio and Uta
![5C194F5C-F4FE-4E4E-9432-CC0D3DD45431](https://user-images.githubusercontent.com/76575962/142589944-d012dd68-3c62-469b-b20f-1def319b8eaf.png), but seems it's hard to make g1t for them, unfortunately.
![B5A28CFE-EA04-4EE9-8397-8E16C57FF1F6](https://user-images.githubusercontent.com/76575962/142589960-b43dd373-0be9-4696-aa0d-cff99c218ebe.png)

**Comment by VitaSmith** [comment]
> The version of G1M and the files inside just like G1MF and so on always changed.

Yes, that is to be expected, because G1M files are associated with a specific game engine, and Koei-Tecmo/Gust will add new extensions and properties to a model, that can be used by that game engine.

My understanding is that the base model description of vertices and surfaces probably doesn't change that much (since the noesis plugin appears to be able to open current `.g1m` models without much trouble), but that there are extensions and properties that are being added, and that we don't usually know much about, that the game engine relies on for a model to work. And that where the `G1M_` and `G1MF` versions come into play.

Also, I see that you have asked a similar question in Joschuka/Project-G1M#12, where they gave you a comprehensive explanation about the versioning.

Finally, if you are using [010 Editor](https://www.sweetscape.com/010editor/), you will find template to help you understand the structure of a `.g1m` model [here]](https://github.com/three-houses-research-team/010-binary-templates/tree/master/Model%20related%20formats).

> And if i want to make some BLUE REFLECTION clothes to BLUE REFLECTION Second Light, could you give me some suggestions？

First of all, I have to point out that I don't currently have a plan to add a utility that deal with `.g1m` files into the gust_tools suite (such as one that would convert `.g1m` to some other format), so if you want to work with models, you will have to look to other applications.

My current understanding is that most of the modders who alter `.g1m` models start by exporting them to _Open Inventor_ `.iv`/`.ib` and somehow import that into Blender, and then perform the reverse operation. And yeah, the utilities that do the import/export may only work with a specific version of G1M. Then again, I have never tried to modify a model, so I can't vouch for that process.

I believe that, if you look hard enough, you should be able to find information on how people manage to modify `.g1m` models and reimport them back into the game, such as on the [LoversLab dedicated thread for BR2 mods](https://www.loverslab.com/topic/179354-blue-reflection-second-light-mod-discussion/) (__WARNING__: NSFW!!!), but, really, all I can provide here are the `gust_g1t` utility that unpack/repack `.g1t` archives that are associated with the `.g1m` models, and, as long as you are not experiencing an issue with `gust_g1t`, I can't really help you out.
