### ISSUE TITLE
repack g1t success but loading char freeze

### ISSUE THREAD

**Issue by ioritree** [VitaSmith/gust_tools#54]
https://drive.google.com/file/d/1P-K27PUl4zPIqiOt8w2b_f4lthbR6L3D/view?usp=sharing
hi!
this is ps4 files.(Fatal Frame: Maiden of Black Water)
unpack/repack gmpk no problem 
but repack g1t >gmpk then into game will freeze at loading character

**Comment by VitaSmith** [comment]
Thanks for the report, but I'm going to need a little more details.

So what you are saying is that if you unpack the `.gmpk` and then repack it without modifying any files, everything works as expected.

What I am unclear is whether you are altering the `.g1t` contained in the `.gmpk` before repacking for the step that you say that fail.

So, is your issue that, when you unpack the `.gmpk`, then unpack a `.g1t` from the newly extracted files, then repack the same `.g1t` __without having modified the textures__, and then reimport it into the `.gmpk`, the game freezes?
Or are you altering the textures before repacking the `.g1t`.

If it's the former, then I will need to know precisely which `.g1t` you extracted and then repacked.
If it's the latter, then I'm afraid it's not a gust_tools issue because if you alter the textures improperly, then the game will reject them, and there are just too many ways you can alter a texture to make them incompatible with a game (and it's not gust_tools' purpose to "fix" textures that have been modified incorrectly).

So I really need to have more data about what `.g1t` you are modifying and how. Without this information, there's just nothing I can do about this issue.

**Comment by ioritree** [comment]
thank you reply.
before edit texture then repack to .g1t >repack to gmpk with .g1m still got freeze at loading character screen ,so try to repack g1t no edit any texture test then repack to .g1t >repack to gmpk with .g1m also got freeze at loading character screen(only know happen on ps4)

**Comment by VitaSmith** [comment]
Ah, I see that the file only contains one `.g1t` and one `.g1m`.

What you need to be aware is that right now, texture types `0x60` and `0x62` are __NOT__ fully supported by `gust_g1t`, and your file uses those types.

If you extract `H_YRI_H.g1t` you will actually see a lot of warnings like:
```
Extracting 'H_YRI_H_PS4.g1t'...
TYPE OFFSET     SIZE       NAME                DIMENSIONS MIPMAPS PROPS
WARNING: Actual texture size is larger than expected size by 0x558
0x60 0x000000dc 0x00003000 H_YRI_H_PS4\000.dds 128x128    6       -
WARNING: Actual texture size is larger than expected size by 0x558
0x60 0x000030f0 0x00001000 H_YRI_H_PS4\001.dds 64x64      5       -
WARNING: Actual texture size is larger than expected size by 0x558
0x60 0x00004104 0x000ab000 H_YRI_H_PS4\002.dds 1024x1024  9       -
WARNING: Actual texture size is larger than expected size by 0xab0
0x62 0x000af118 0x00056000 H_YRI_H_PS4\003.dds 512x512    8       -
WARNING: Actual texture size is larger than expected size by 0xab0
0x62 0x0010512c 0x00156000 H_YRI_H_PS4\004.dds 1024x1024  9       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x0025b140 0x002ab400 H_YRI_H_PS4\005.dds 2048x1024  9       -
WARNING: Actual texture size is larger than expected size by 0x4b0
0x60 0x00506554 0x00055a00 H_YRI_H_PS4\006.dds 1024x512   8       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x0055bf68 0x000ab400 H_YRI_H_PS4\007.dds 1024x512   8       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x0060737c 0x0002b400 H_YRI_H_PS4\008.dds 512x256    7       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x00632790 0x0000b400 H_YRI_H_PS4\009.dds 256x128    6       -
WARNING: Actual texture size is larger than expected size by 0x4b0
0x60 0x0063dba4 0x00155a00 H_YRI_H_PS4\010.dds 2048x1024  9       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x007935b8 0x002ab400 H_YRI_H_PS4\011.dds 2048x1024  9       -
WARNING: Actual texture size is larger than expected size by 0x960
0x62 0x00a3e9cc 0x002ab400 H_YRI_H_PS4\012.dds 2048x1024  9       -
WARNING: Actual texture size is larger than expected size by 0xab0
0x62 0x00ce9de0 0x00006000 H_YRI_H_PS4\013.dds 128x128    6       -
WARNING: Actual texture size is larger than expected size by 0xab0
0x62 0x00cefdf4 0x00006000 H_YRI_H_PS4\014.dds 128x128    6       -
```

This means that repacking is unlikely to work. As a matter of fact, if you look at the mipmap for `002.dds` you will find that it is not extracted correctly:

![002](https://user-images.githubusercontent.com/32225969/148574244-04967b18-c047-46fb-a396-75a37581a951.png)

This also means that repacking will not work, and that you won't be able to edit the file.

I'm afraid that I am concentrating my efforts mostly on PC games, and trying to support other platform, such as PS4, takes a lot of time that I don't actually have. So some texture formats, like `0x60` and `0x62` are only partially supported, and will remain that way until I find some time to look into it (which may never happen at all), or until somebody else sends a patch.

Therefore I will close this issue as this is not something I am planning to fix in the short term. Sorry.

**Comment by ioritree** [comment]
thank you , bother you many time :)
