### ISSUE TITLE
FabStyle (3DS) .g1t files

### ISSUE THREAD

**Issue by RocketRobz** [VitaSmith/gust_tools#7]
I'm working on a translation of FabStyle for Nintendo 3DS.
It seems the graphics are stored in .g1t files, but when trying to extract them, I get this:
```
ERROR: Unsupported texture type (0x45)
```
Any chance of adding support for that texture type?

Here's a zip containing 3 .g1t files.
[Title.zip](https://github.com/VitaSmith/gust_tools/files/4011907/Title.zip)

UPDATE: There are more unsupported formats: 0x3C, 0x3D, 0x45, 0x47, 0x48

The tool supports 0x09, but gives these errors:
```
Extracting 'BrandLogo.g1t'...
OFFSET   SIZE     NAME              DIMENSIONS MIPMAPS
0000008c 00080008 BrandLogo\000.dds 256x512    1
ERROR: Can't create file 'BrandLogo\000.dds'
00080094 00080008 BrandLogo\001.dds 256x512    1
ERROR: Can't create file 'BrandLogo\001.dds'
0010009c 00080008 BrandLogo\002.dds 256x512    1
ERROR: Can't create file 'BrandLogo\002.dds'
001800a4 00080008 BrandLogo\003.dds 256x512    1
ERROR: Can't create file 'BrandLogo\003.dds'
002000ac 00080008 BrandLogo\004.dds 256x512    1
ERROR: Can't create file 'BrandLogo\004.dds'
002800b4 00080008 BrandLogo\005.dds 256x512    1
ERROR: Can't create file 'BrandLogo\005.dds'
003000bc 00080008 BrandLogo\006.dds 256x512    1
ERROR: Can't create file 'BrandLogo\006.dds'
003800c4 00080008 BrandLogo\007.dds 256x512    1
ERROR: Can't create file 'BrandLogo\007.dds'
004000cc 00080008 BrandLogo\008.dds 256x512    1
ERROR: Can't create file 'BrandLogo\008.dds'
004800d4 00080008 BrandLogo\009.dds 256x512    1
ERROR: Can't create file 'BrandLogo\009.dds'
005000dc 00080008 BrandLogo\010.dds 256x512    1
ERROR: Can't create file 'BrandLogo\010.dds'
005800e4 00080008 BrandLogo\011.dds 256x512    1
ERROR: Can't create file 'BrandLogo\011.dds'
006000ec 00080008 BrandLogo\012.dds 256x512    1
ERROR: Can't create file 'BrandLogo\012.dds'
006800f4 0008005c BrandLogo\013.dds 256x512    1
ERROR: Can't create file 'BrandLogo\013.dds'
```

**Comment by VitaSmith** [comment]
Type `0x45` is relatively easy (it's 24-bit tiled RGB), so I've added it to the latest version of the application:

![000](https://user-images.githubusercontent.com/32225969/71901943-f2496200-3158-11ea-8510-152bc5ec3c56.png)

![001](https://user-images.githubusercontent.com/32225969/71901955-f70e1600-3158-11ea-82bb-0e3d38a4b79a.png)

![002](https://user-images.githubusercontent.com/32225969/71901973-fd9c8d80-3158-11ea-95c2-07b637acec65.png)

![000](https://user-images.githubusercontent.com/32225969/71902060-2886e180-3159-11ea-9f8a-5691fb7bf85b.png)

![001](https://user-images.githubusercontent.com/32225969/71902069-2d4b9580-3159-11ea-85af-723f9369410c.png)

Note that, because the DS images are flipped, you will need to use the new `-f` flag (flip) with `gust_g1t` when unpacking or repacking the textures, otherwise they will appear upside down:

![000-flipped](https://user-images.githubusercontent.com/32225969/71902249-90d5c300-3159-11ea-9b46-f35d7077692f.png)

For instance, you will need to use:
```
gust_g1t -f Logo.g1t
```

For the other types however, I'm not planning to add support for them myself, sorry. I just don't have the time for that. I tried to see what I could do to support types `0x3C` and `0x3D` but it would just take way too much time to do it and there is only so much time I can invest on a side project.
