### ISSUE TITLE
gust_enc: bug characters with accent

### ISSUE THREAD

**Issue by GuhLucena** [VitaSmith/gust_tools#70]
Accent error in Atelier Sophie 2 when compiling file `/Saves/Text_EN/strCombineAll.xml.e`

![2023010915081800 - Copia](https://user-images.githubusercontent.com/60260087/211379332-14688a7f-cec1-4d0a-ac6d-c0aca39ef82d.jpg)

https://barrelwisdom.com/sophie2/items/pendegrun/en
![image](https://user-images.githubusercontent.com/60260087/211379635-90e80b96-102c-413a-b2c9-7fde7aa87616.png)

**Comment by VitaSmith** [comment]
Hmm, I'm not seeing the issue with the decoded `.xml`. Are you absolutely sure you didn't alter the XML encoding?

Please perform the following:
1. Copy `strcombineall.xml.e` and ` strcombineall.xml` to a directory
2. Run `gust_enc.exe strcombineall.xml.e`
3. Binary compare `strcombineall.xml` (which will have been created by the command above) and `strcombineall.xml.bak` (which, also will have been renamed from the original `strcombineall.xml` by the command above). If running from a Windows command prompt, you can use `fc /b strcombineall.xml strcombineall.xml.bak`. There should be no differences.
4. Now run `gust_enc.exe strcombineall.xml`. This will create a new `strcombineall.xml.e`
5. Delete `strcombineall.xml` (since you have validated that you have an identical copy in `strcombineall.xml.bak`) and once again run: `gust_enc.exe strcombineall.xml.e`
6. Run a binary comparison of `strcombineall.xml` and `strcombineall.xml.bak` again. There should be no differences.
7. If you have validated that there is no difference, try to use the `gust_enc` generated `strcombineall.xml.e` in the game and see if you still see an accent issue. If you don't see it, then it means that the problem you have is due to your editing of the file and not gust_tools.

**Comment by GuhLucena** [comment]
thanks, my file that was corrupted
