### ISSUE TITLE
How to batch convert?

### ISSUE THREAD

**Issue by Arthandas** [VitaSmith/gust_tools#79]
I have 465 g1t files, I want to convert them all to dds but gust_g1t.exe allows dropping only a single file at a time.

**Comment by VitaSmith** [comment]
Just write a batch file. There are plenty of resources online that explain how you can write a batch script with a `for` loop that will process each file.

Please understand that it will never be gust_g1t's job to automate that part, because, unlike the g1t to DDS conversion, that is something that can already be solved natively by your OS.
