### ISSUE TITLE
gust_pak: Support for Atelier Marie Remake

### ISSUE THREAD

**Issue by Masquerade64** [VitaSmith/gust_tools#81]
https://store.steampowered.com/app/2138090/
Atelier Marie Remake has been released on Steam, please may gust_pak be updated with the key for this game? The paks cannot be extracted with current version.

`Extracting 'PACK11_00.PAK'...
Detected A22/64-bit PAK format
Using A23 master key

OFFSET    SIZE     NAME
ERROR: Failed to decode filename for entry 0`

Sample file: https://gofile.io/d/ocz2dd

**Comment by VitaSmith** [comment]
Thanks. I should have a new release of gust_tools that supports Atelier Marie (A25) in a few hours.

For reference, the master decoding key for this game is: `vh0WESTtbeBuTwWusr4EVusMi4TbLmjQ`

Note that every recent Atelier game has a different master key for decoding PAK's, which is why you won't be able to extract the content until I add the key to gust_tools. Oh, and in case Gust's lawyers are watching, I have not purchased the game yet, so I did not pick the key from reverse engineering the executable, but derived it directly from the PAK data.

```
Extracting 'PACK11_00.PAK'...
Detected A22/64-bit PAK format
Using A25 master key

OFFSET    SIZE     NAME
000000180 0000fb6f \data\x64\character\anv_25glasses\anv_25glasses.elixir.gz
00000fcef 00093094 \data\x64\character\anv_25glasses\anv_25glasses.g1t
Creating '.\PACK11_00.json'
```

![000](https://github.com/VitaSmith/gust_tools/assets/32225969/a88fe56a-0042-4a0e-8192-f5adf9539b6f)
