### ISSUE TITLE
Gust G1T fails to extract a DDS texture from a Fatal Frame 4 character model

### ISSUE THREAD

**Issue by Jupisoft111** [VitaSmith/gust_tools#84]
Hello, I just found what I believe might be a new possible "bug", since the Gust G1T can't seem to properly export the DDS texture "020.dds", but I don't know if it's something from the game or not, or if the game might crash if that texture ends up missing. Thanks a lot in advance. Note: I remember having posted something similar long ago, but I can't remember right now if it was related or not, sorry if I'm mistaken and have a nice day :-)

I just uploaded ALL the original files here, just in case they are needed:
[Mediafire link](https://www.mediafire.com/file/itfqcl4swiwh9al/Bug+DDS+Texture+020,+H_RUK_Q.rar/file)

[H_RUK_Q.zip](https://github.com/VitaSmith/gust_tools/files/12263723/H_RUK_Q.zip)
[H_RUK_Q 020 DDSs.zip](https://github.com/VitaSmith/gust_tools/files/12263725/H_RUK_Q.020.DDSs.zip)

**Comment by VitaSmith** [comment]
This is a 1 pixel by 1 pixel texture, so it doesn't really matter if you can edit it or not:
```
0x01 0x01cb0d44 0x00000004 H_RUK_Q\020.dds 1x1        1       -
```
The thing is, you can repack the texture into a `.g1t` and there will be no issue (you can validate this by extracting `H_RUK_Q.g1t` and the recreating it with gust_g1t and comparing with the original, and you will find that they are identical).

So, the only small problem is that most DDS editors won't be able to open this `1x1` texture, and this appears to have to do with having the `DDS_NORMAL` flag being applied in the DDS picture format field. From what I can see, you're not supposed to have that flag for RGBA textures (even though the `.g1t` indicates that this texture is meant to be used for normals) so I will make sure to remove it in a next version, and then you will be able to "edit" that `1x1` texture.

I am however not going to produce a new release just for that, since, as long as this only happens with `1x1` dummy textures and `gust_g1t` will repack the `.g1t` just fine, this is not a showstopper.

**Comment by Jupisoft111** [comment]
Thanks a lot for all the info, then for now I'll just ignore the ones that seem to be 1x1 until you release a new version (I can wait). So thanks a lot once again, because I was a bit worried that the resulting mods might have some kind of errors in them :-)
